---
lb_control_type: nginx   # nginx（dev）または alb（prod）
lb_control_host: lb01
lb_control_action: drain
lb_control_listen_port: 80
lb_control_proxy_backup_generations: 3
lb_control_upstream_backup_generations: 9
