---
- name: LB に nginx をセットアップする
  hosts: lb
  roles:
    - nginx

- name: LB の初期プロキシ設定を行う
  hosts: web
  run_once: true
  tasks:
    - name: LB に proxy.conf・upstream.conf を配置する
      ansible.builtin.include_role:
        name: lb_control
      vars:
        lb_control_action: restore

- name: ローリング更新
  hosts: web
  serial: 1
  any_errors_fatal: true

  pre_tasks:
    - name: LB からサーバを切り離す
      ansible.builtin.include_role:
        name: lb_control
      vars:
        lb_control_action: drain

  roles:
    - nginx

  post_tasks:
    - name: 動作確認
      ansible.builtin.include_role:
        name: healthcheck

    - name: LB にサーバを組み込む
      ansible.builtin.include_role:
        name: lb_control
      vars:
        lb_control_action: restore
