---
- name: Nginx LB タスクを実行する
  ansible.builtin.include_tasks: nginx.yml
  when: lb_control_type == 'nginx'

- name: ALB タスクを実行する
  ansible.builtin.include_tasks: alb.yml
  when: lb_control_type == 'alb'
